config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # resources :films
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web=> '/sidekiq'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/articles", to: "articles#index"
  root "articles#index"
  resources :films do
    collection do
      get :omdb_search
      post :omdb_import
    end
    resources :comments, only: %i[create edit update destroy]
  end
  # Defines the root path route ("/")
  # root "posts#index"
  resource :profile, only: %i[edit update], controller: :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true
    belongs_to :user
    validates :body, presence: true, length:{minimum:10, maximum: 500}
    has_many :comments, as: :commentable, dependent: :destroy
    after_create :send_email
    private

    def send_email
      CommentMailer.with(user: user, comment: self).created.deliver_later
      # CommentMailer.with(user: user, comment: self).created.deliver_now
    end
end

app/models/film.rb
class Film < ApplicationRecord
    GENRES = %w[action comedy drama horror romance thriller sci-fi fantasy animation documentary musical western].freeze
    has_many :comments, as: :commentable, dependent: :destroy
    # validates :name, :year_of_creation, presence:true
    # validates :description, length: {minimum: 10}
    # validates :year_of_creation, numericality: { only_integer: true, greater_than_or_equal_to: 2000 }
    # validates :director, presence:true
    # validates :duration, numericality: { only_integer: true, greater_than_or_equal_to: 30 }
    # validates :name, uniqueness: { scope: :year_of_creation}
    # validate :genres_validation
    
    private

    def genres_validation
    unless genres.is_a?(Array) && genres.any?{ |genre|genre.present?}
        errors.add("genres","invalid")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy

  has_one_attached :avatar do |attachable|
    attachable.variant :tiny, resize_to_limit: [50, 50]
  end

  def full_name
    return email if first_name.blank? && last_name.blank?

    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    protect_from_forgery prepend: true
    before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :film, only: :create
    before_action :find_comment, except: :create
  
    def create
      @comment = Comment.new(comment_params.merge!(user: current_user))

        if @comment.save
            redirect_to film_path(@film)
        else

        end
    end

    def edit
      authorize @comment
      @comment = Comment.find(params[:id])
    end

    def destroy
      authorize @comment
        @comment.destroy!
    
        # respond_to do |format|
        #   format.html { redirect_to films_url, notice: "Comment was successfully destroyed." }
        #   format.json { head :no_content }
        # end
    end

    def update
        # @comment = Comment.find(params[:id])
        
        @comment.assign_attributes(comment_params)

        if @comment.save
            redirect_to @comment.commentable, notice: 'Comment updated'
          else
            flash[:error] = @comment.errors.full_messages.join(", ")
            render :edit
        end
        
    end

    private
    def comment_params
        params.require(:comment).permit(:body, :commentable_id, :commentable_type)
        # .merge!(commentable: film, user: current_user)
    end

    def film
        @film = Film.find(params[:film_id])
    end

    def find_comment
      @comment = Comment.find(params[:id])
      authorize @comment
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]
  

  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
    @omdb = OmdbClient.new
    @omdb_film = @omdb.find_by_title(@film.name)
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy!

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def omdb_search
    if params[:search_query].present?
      @omdb = OmdbClient.new

      # @search_results = @omdb.search(params[:search_query])['Search']
      res = @omdb.search(params[:search_query])
      @search_results = res['Search']
    end
  end

  def omdb_import
    # @omdb = OmdbClient.new

    # @omdb_film = @omdb.find_by_id(params[:omdb_id])

    # @film = Film.new(
    #   name: @omdb_film['Title'],
    #   cover_image_url: @omdb_film['Poster'],
    #   year_of_creation: @omdb_film['Year'],
    #   description: @omdb_film['Plot'],
    #   duration: @omdb_film['Runtime'],
    #   director: @omdb_film['Director'],
    #   genres: @omdb_film['Genre'].present? ? @omdb_film['Genre'].split(', ') : []
    # )
    # if @film.save
    #   redirect_to @film
    # else
    #   flash[:error] = @film.errors.full_messages.join(", ")
    #   render :omdb_search
    # end
    FilmsImportJob.perform_later(params[:omdb_id], current_user)
    flash[:notice] = 'Movie will be imported soon. Thanks!'
    redirect_to films_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:name, :description, :year_of_creation, :director, :duration, :cover_image_url, genres:[])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def edit
    end
  
    def update
      if current_user.update(profile_params)
        flash[:notice] = 'Profile updated'
        redirect_to root_path
      else
        flash[:alert] = current_user.errors.full_messages.join(", ")
      end
    end
  
    private
  
    def profile_params
      params.require(:user).permit(:first_name, :last_name, :avatar)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/articles/index.html.erb
<h1>ruby</h1>
<h2><a href="<%= films_path%>">Films</a></h2>

app/views/comments/_form.html.erb
<% if comment_to.is_a?(Film) %>
  <% film = comment_to %>
  <h4>Create</h4>
<% elsif comment_to.is_a?(Comment) %>
  <% film = comment_to.commentable %>
  <h5>Reply</h5>
<% end %>
<%= form_for :comment, url: film_comments_path(film) do |form| %>
<%= form.hidden_field :commentable_type, value: comment_to.class.name %>
  <%= form.hidden_field :commentable_id, value: comment_to.id %>
    <%= form.text_field :body %>
    <%=form.submit%>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment)%>

app/views/comments/edit.html.erb
<%=turbo_frame_tag(dom_id(@comment)) do %>
    <h3>Edit comment <%= @comment.id%> (by <%= @comment.user.email%>)</h3>
    <%= form_for @comment, url: film_comment_path(@comment, film_id: @comment.commentable_id)  do |form| %>
        <%= form.text_field :body %>
        <%=form.submit%>
    <% end %>
<%end%>

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Name:</strong>
    <%= film.name %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= film.genres.filter_map{|g| g.titleize if g.present?}.join(', ') %>
  </p>


  <p>
    <strong>Description:</strong>
    <%= film.description %>
  </p>

  <p>
    <strong>Release year:</strong>
    <%= film.year_of_creation %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= film.director %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= film.duration %>
  </p>

</div>

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
        <% film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  <%= form.label :genre, style: "display: block" %>
  <%= form.select :genres, Film::GENRES, multiple:true %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :year_of_creation, style: "display: block" %>
    <%= form.number_field :year_of_creation %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Films</h1>

<div id="films">
  <% @films.each do |film| %>
  <% if film.cover_image_url %>
    <h2><%= image_tag(film.cover_image_url) %></h2>
  <% end %>
    <%= render film %>
    <p>
      <%= link_to "Show this film", film %>
    </p>
  <% end %>
</div>

<%= link_to "New film", new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/omdb_search.html.erb
<h1>Omdb search</h1>
<%= form_tag omdb_search_films_path, method: :get do %>
  <div style='margin-bottom: 10px;'>
    <%= label_tag :search_query %>
    <%= text_field_tag :search_query, params[:search_query] %>
  </div>

  <%= submit_tag 'Search' %>
<% end %>
<% if @search_results.present? %>
  <table>
    <thead>
    <th>Title</th>
    <th>Year</th>
    <th>Image</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <% @search_results.each do |film| %>
      <tr>
        <td><%= film['Title'] %></td>
        <td><%= film['Year'] %></td>
        <td>
          <% begin %>
            <%= image_tag(film['Poster']) %>
          <% rescue Sprockets::Rails::Helper::AssetNotFound %>
            <%= image_tag('test_image.jpg') %>
            <p>No image</p>
          <% rescue StandardError %>
            <p>Custom error</p>
          <%end%>
        </td>
        <td>
          <%= form_tag omdb_import_films_path, method: :post do %>
          <%= hidden_field_tag :omdb_id, film ['imdbID'] %>
            <%= submit_tag 'Import' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


<%# (omdb_id: film['imdbID']) %>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @film.cover_image_url %>
  <h2><%= image_tag(@film.cover_image_url) %></h2>
<% end %>

<%= render @film %>
<div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %>

  <%= button_to "Destroy this film", @film, method: :delete %>


<hr/>

<article>
  <h3> OMDB info </h3>
  <p>
    <%= @omdb_film %>
  </p>
</article>

<hr/>
  
<% @film.comments.includes(:user).each do |comment| %>
  <%=turbo_frame_tag(dom_id(comment)) do %>
  <p><%=comment.body %>(by <%= comment.user.email%>)
    <div>
      <%= render partial: 'comments/form', locals: { comment_to: comment } %>
    </div>
   <% if policy(comment).edit?%>
  <%= link_to('edit', edit_film_comment_path(comment, film_id: comment.commentable.id)) %> 
   <% end %>
    <% if policy(comment).destroy?%>
  <%= link_to('destroy', film_comment_path(comment, film_id: comment.commentable), method: :delete, data: {turbo_method: :delete}) %> 
  
    <% end %>
    <div class='container small'>
        <% comment.comments.includes(:user).each do |sub_comment| %>
          <%= sub_comment.body %> (by <%= sub_comment.user.email %>)
          <br/>
        <% end %>
      </div>
    </p>
  <%end%>
<%end%>
<%= render partial: 'comments/form', locals: { comment_to: @film} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmtr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmtr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<h1><%= current_user.full_name %></h1>
<% if current_user.avatar.attached? %>
  <%= image_tag(current_user.avatar) %>
<% end %>

<article>
  <%= form_for(current_user, url: profile_path(current_user), method: :put) do |f| %>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div>
      <%= f.file_field :avatar %>
    </div>
    <%= f.submit %>
  <% end %>
</article>

app/views/shared/_header.html.erb
<%= button_to "Logout" , destroy_user_session_path, method: :delete, style: "width: auto; padding: 5px 10px; margin-right: 10px;" %>
 
 
 <%= image_tag(current_user.avatar.variant(:tiny)) if current_user.avatar.attached? %>
    <%= link_to(current_user.full_name, edit_profile_url) %>
 <%= link_to 'Search OMDB', omdb_search_films_path %>